title: Kjeldhansen.dk
description: Public website for Kjeld Hansen 
author:
  name: Daniel Aakjær Sørensen

host: 0.0.0.0
repository: danielaakjaer/kjeldhansen.github.io

sass:
  style: compressed
  sass_dir: assets/_scss

exclude:
  - "node_modules"
  - "bower_components/popper.js/docs"
  - "bower_components/bootstrap/index.html"
  - "bower_components/bootstrap/site"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "package-lock.json"
  - "package.json"
  - "README.md"

emails:
  contact: vvs@kjeldhansen.dk

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: "bower_components"
    values:
      sitemap: false