- title: Ifø Sign WC med lukket S-lås
  text: >-
    Levering og montering af Ifø Sign wc model 6860 med rengørringsvenlig
    glasur, 4/2 liters skyl og hel cisternekappe for nemmere rengørring sat
    Fresh wc (hygiejnisk doseringsløsning i skylleknappen) monteres med hvidt
    hårdt Pressalit Sign wc sæde model 724. Inkl. udsmidning af det gamle wc.
  price: Tilbud 4.800,00 kr. inkl. moms
  image_path: /assets/img/products/001.jpg
  vat-included: true
- title: Ifø Spira WC med lukket S-lås
  text: >-
    Levering og montering af Ifø Spira wc Rimfree med skjult s-lås model 6260
    med rengørringsvenlig glasur, 4/2 liters skyl og hel cisternekappe for
    nemmere rengørring samt Fresh wc (hygiejnisk doseringsløsning i
    skylleknappen) monteres med hvidt Ifø Spira wc sæde med quick release model
    99492 Inkl. udsmidning af det gamle wc.
  price: Tilbud 5.300,00 kr. inkl. moms
  image_path: /assets/img/products/002.jpg
  vat-included: true
- title: Ifø Spira WC med P-lås
  text: >-
    Ifø Spira wc med P-lås model 6262 med rengørringsvenlig glasur og hel
    cisternekappe for nemmere rengørring samt Fresh wc (hygiejniske
    doseringsløsning i skylleknappen) monteres med hvidt Ifø Spira wc sæde.
    Inkl. udsmidning af det gamle wc.
  price: Tilbud 5.600,00 kr. inkl. moms
  image_path: /uploads/ifø-spira-p-lås.jpg
  vat-included: true
- title: Ifø Sign WC kort model
  text: >-
    Ifø Sign wc kort model 6832 med rengørringsvenlig glasur og hel
    cisternekappe for nemmere rengørring samt Fresh wc (hygiejnisk
    doseringsløsning i skylleknappen) monteres med hvidt hårdt Pressalit Sign wc
    sæde model 724. Inkl. udsmidning af det gamle wc.
  price: Tilbud 5.990,00 kr. inkl. moms
  image_path: /uploads/004.jpg
  vat-included: true
- title: Ifø Spira WC med åben S-lås
  text: >-
    Levering og montering af Ifø Spira wc Rimfree med åben s-lås model 6270 med
    rengørringsvenlig glasur, 4/2 liters skyl og hel cisternekappe for nemmere
    rengørring samt Fresh wc (hygiejnisk doseringsløsning i skylleknappen)
    monteres med hvidt Ifø Spira wc sæde med quick release model 99492 Inkl.
    udsmidning af det gamle wc.
  price: Tilbud 5.400,00 kr. inkl. moms
  image_path: /uploads/ifø-åben.jpg
  vat-included: true
- title: Levering og montering
  text: >-
    Levering og montering af Hansgrohe Focus 100 håndvaskbatteri med løft op
    bundventil.

    Forbehold for at der kan lukkes for vandet under vask/i lejlighed.
  price: Pris 1.900,00 kr. inkl. moms
  image_path: /uploads/hg-focus.jpg
  vat-included: true
- title: Levering og montering
  text: >-
    Levering og montering af Grohe Essence krom håndvaskbatteri med løft op
    bundventil.

    Forbehold for at der kan lukkes for vandet under vask/i lejligheden.
  price: Tilbud 1.800,00 kr. inkl. moms
  image_path: /uploads/grohe-essence-håndvaskbatteri.jpg
  vat-included: true
- title: Gustavsberg vask
  text: |-
    Nautic porcelænsvask 60x46 cm.
    Førpris 777,00 kr. inkl. moms.
  price: Tilbud 500,00 kr. inkl. moms
  image_path: /uploads/gustavsberg-vask.jpg
  vat-included: true
- title: Ifø glasdør
  text: |-
    Space 2000 nichedør med alu profiler og frostglas med knopgreb.
    80 cm bred og 190 cm høj.
    Før pris 3.266,00 kr. inkl. moms.
  price: Tilbud 2.500,00 kr. inkl. moms
  image_path: /uploads/ifø-glasvæg.jpg
  vat-included: true
- title: Dansani Luna
  text: |-
    Vaskeskab i Coffee med 2 skuffer og blankkrom greb 100 cm.
    Menuet hvid porcelænsvask 100 cm.
    Spejlskab i Coffee med integreret belysning 100 cm.
    Højskab i Coffee med 2 låger og 2 skuffer og krom greb.
    Udstillingsmodel, ekskl. håndvaskbatteri.

    Førpris for sæt 23.830,00 kr. inkl. moms.
  price: Tilbud 7.000,00 kr.
  image_path: /uploads/dansani-luna-coffee-ny-butik-1.jpg
  vat-included: true
- title: Dansani Calidris
  text: |-
    Square hvid marmorvask 115,2 cm.
    Vaskeskab i Teak med 2 skuffer 115,2 cm.
    Spejl i Teak med 2 stk. lampetter og afbryder 115,2 cm.
    2 stk. greb i smooth blank krom.
    Udstillingsmodel. Ekskl. håndvaskbatteri.

    Førpris for sæt 18.110,00 kr. inkl. moms.
  price: Tilbud for sæt 7.000,00 kr. inkl. moms.
  image_path: /uploads/dansani-calidris-teak-3-1.jpg
  vat-included: true
- title: Dansani Luna
  text: |-
    Kantate hvid porcelænsvask 71 cm.
    Vaskeskab i hvid højglans med 2 skuffer og krom greb 70 cm.
    Spejlskab med integreret lys i top og bund 70 cm.
    Før pris for sæt 13.855,00 kr. inkl. moms.
    Udstillingsmodel. Ekskl. håndvaskbatteri.
  price: Tilbud 5.500,00 kr. inkl. moms
  image_path: /uploads/dansani-luna-kantate-70cm1.jpg
  vat-included: true
- title: Dansani Luna
  text: |-
    Menuet hvid porcelænsvask 51 x 36 cm.
    Vaskeskab i Champagne med 2 skuffer og krom greb 50 cm.
    Spejlskab i Champagne med integreret belysning i top og bund 50 cm.
    Før pris for sæt 10.430,00 kr. inkl. moms.

    Udstillingsmodel. Ekskl. håndvaskbatteri.
  price: Tilbud 4.000,00 kr. inkl. moms.
  image_path: /uploads/dansani-luna-champagne.jpg
  vat-included: true
- title: Ifø Sign møbelpakke
  text: >-
    Ifø Sign møbelpakke med porcelænsvask og vaskeskab i hvid med 2 låger og
    greb.

    Bredde 51 cm, Dybde 29 cm, Højde 68,5 cm.

    Ekskl. armatur og montering.
  price: Tilbud 2.700,00 kr. inkl. moms.
  image_path: /uploads/sign-møbelpakke.png
  vat-included: true